### ISSUE TITLE
OSF will impose 50GB limit on storage

### ISSUE THREAD

**Issue by adswa** [datalad/datalad-osf#129]
That's sad: Public projects will be limited to 50GB, private to 5GB. https://www.cos.io/blog/shared-investment-in-osf-sustainability

**Comment by mih** [comment]
Nothing we can do about this, so closing.

**Comment by da5nsy** [comment]
Since this, the following, from [here](https://github.com/datalad/datalad-osf/blob/main/docs/source/intro.rst) is out of date:

`At the moment, a the OSF storage provides virtually unlimited storage capacity. As long as individual files are smaller than 5GB, any amount of data can be uploaded to the OSF.`

**Comment by adswa** [comment]
thanks for highlighting this, I'll update!
