### ISSUE TITLE
Implement convenience command to configure an OSF "sibling" for a dataset

### ISSUE THREAD

**Issue by mih** [datalad/datalad-osf#15]
DataLad has others like this (e.g. `create-sibling-github`). While the setup with `git-annex initremote` isn't too crazy, it is missing the project creation on OSF. It would make sense to provide a `create-sibling-osf` that is capable of automating this step.

**Comment by adswa** [comment]
I've assigned @bpoldrack for a start to lead this parallel development effort

**Comment by bpoldrack** [comment]
Started looking into this. The idea would be to have some helper functions that can take care of setting up the OSF end and of calling `initremote` with the appropriate parameters. Those can then be used from within a `datalad` command (that can then operate on a datalad dataset, read its configs, do the its thing for an entire hierarchy of datasets, etc.) and/or from a simple convenience script for users that doesn't depend on datalad. Therefore we could have full integration w/ datalad, but also a stand-alone version.

I can create a project via OSF's API - so that part will work fine.
However, it doesn't seem to be possible to link a GitHub/GitLab/etc repository to a project via API. This will require a manual step on OSF for now. Kinda limits the utility of this convenience layer.

**Comment by bpoldrack** [comment]
FTR: All of this refers to usecase in #10.

**Comment by kousu** [comment]
Correct me if I'm wrong, but wouldn't this feature sit outside this codebase? It's a datalad-level wrapper. This project doesn't depend on datalad, except for tests, and even those are really only calling out to `git-annex testremote`.

**Comment by bpoldrack** [comment]
Yes, @kousu  - I'm doing both.
I have:
- a routine to create an OSF project. That one can then be moved into osfclient, when we got all parts working.
- two standalone convenience scripts, that can come with the special remote and don't depend on datalad:
     - one for making the initremote call w/o a user being required to know all the mandatory configs (just pass project ID + objpath)
     - one for creating the project in the first place and then do the above accordingly (takes project title rather than bothering the user with the ID)
 - an actual datalad command that does those things as an alternative. This will allow for more things, like doing those setups recursively for lots of (sub-)datasets

And yes - I'm aware of #30. Will adapt. Those components are created the same way. Will include that.

**Comment by adswa** [comment]
Closing this, this is done! :tada:
