### ISSUE TITLE
Support token auth

### ISSUE THREAD

**Issue by mih** [datalad/datalad-osf#17]
osfclient can do it now.

**Comment by mjboos** [comment]
Here are some thoughts/questions on directions this could take, input by people more experienced in datalad/git-annex-experienced people is very welcome:
-Should we support helper functions that allow an user to extract his ORCID token or do we rely on the user himself? This would be possible for ORCID, but likely overkill, and probably not reasonable for institution login.
-AnnexRemote supports a config & info that "makes `git annex initremote` work better, because it can check the user's input,  and can also display a list of settings with descriptions." -- I think it makes sense to use that instead of environment variables - both for oauth, as well as passwords/usernames - but I am unsure if this would pose problems in datalad extensions
-If we don't want to use the config or special/exportremote, the easiest solution is again an environment variable or a config file in which the user has to save it himself - similar to how datalad handles Github oauth for sibling datasets

**Comment by mih** [comment]
I have no input on (1). Re (2) I think more options are better. Environment variables are nice, because they leave no trace in the datasets. Anything that is given to `initremote` will end up being commited (and shared) in the repository -- hence not an option for public datasets. If we were to use DataLad, we could use its config mechanism that can pull from the environment, but also from various git-config sources. But @kousu wanted to have the special remote code by standalone.

**Comment by kousu** [comment]
1. I don't think an ORCID token is the same kind of token here. ORCID passes OAuth tokens to authenticate you to OSF.io as your ORCID; [OSF tokens](https://osf.io/settings/tokens) authenticate your bots to OSF as your OSF account.

**Comment by kousu** [comment]
I ended up following https://git-annex.branchable.com/special_remotes/webdav/. It seems kind of quirky; I would try to figure out a way to use the system keychain or pass(1), or maybe put the creds in `git config remote."osf".token` -- people do that for git+https:// sometimes, why not special remotes too? -- but there's value in taming the hydra.

**Comment by mjboos** [comment]
>     1. I don't think an ORCID token is the same kind of token here. ORCID passes OAuth tokens to authenticate you to OSF.io as your ORCID; [OSF tokens](https://osf.io/settings/tokens) authenticate your bots to OSF as your OSF account.

That's right, thanks for clarifying.

**Comment by mih** [comment]
We have #42 still open, but tokens are already in use now after #60
